;; https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-11.html#%_thm_1.12
(define (pascals-triangle row col)
  (cond ((= row 1) 1)
        ((or (= col 1) (= col row)) 1)
        (else (+ (pascals-triangle (- row 1) (- col 1))
                 (pascals-triangle (- row 1) col)))))

(define (print-pascals-triangle rows)
  (define (print-row row)
    (define (col-iter col)
      (display (pascals-triangle row col))
      (display " ")
      (if (= row col)
          (newline)
          (col-iter (inc col)))
      )
    (col-iter 1))
  (define (row-iter row)
    (print-row row)
    (if (= row rows)
        (newline)
        (row-iter (inc row))))
  (row-iter 1))
